### ISSUE TITLE
Finished Auth

### ISSUE THREAD

**Issue by happler** [happler/PageTurners#1]
I believe I've finished the auth both features and styling.  please let me know what I still need to work on

**Comment by mashuDuek** [comment]
Hi Harry, looks good. Comments below: 

1. Landing page: you can scroll way past the form and there is nothing to see past it. Should not be able to scroll to where there is nothing for the user. Also, Goodreads has an image stretching across the bottom of their landing page. 
2. Continue with Demo button does not work, at all. 
3. There should be placeholders, at least in one of the two input fields. Check goodreads form.
4. I don't see error handling when logging in, and i don't have account. 

Thats a nice handful for now. 

Ping me back when this is all done.

**Comment by happler** [comment]
Alright, I fixed those issues, and added a little space between the elements on the login (they were looking a little cramped) as well as the space inside the text entry.  Those changes should be live now.  Let me know what else I still need to fix

**Comment by mashuDuek** [comment]
Okay, now that you have your forms all nice and tidy, we need to look at what goodreads is doing. Their landing page is very populated with a bunch of stuff including a tiny login form. So, we need to have a nice landing page, like they do with a small form to login, as well as the demo button next to that login. On click of sign-up we take them to the /signup route, and from there you should be able to click the "log in" button which should take you to the /login route, and that does display only the login form. 

The good thing about this feature (auth), which for you is huge because of that populated landing page, is that once its done you already have the styling down for most of the app. 

Let me know if you have any questions!

**Comment by mashuDuek** [comment]
I created a user: (username: 'mashu mashu', pw: 'mashu mashu'), successfully logged in and signed out. But then when I trie to login from the './' form it redirects me to the '/login' and says username can't be blank. 

Same thing when I try to signup from the './' form.

**Comment by happler** [comment]
oh shoot, that's embarrassing.  Should be working now

**Comment by mashuDuek** [comment]
Close this issue! Good job fixing what I asked.
